### PR TITLE
Support cross compile for ARM architecture.

### PR DESCRIPTION
**Pull request by skydiator**
Allow people to use nassl on the ARM architecture.

### CODE REVIEW

**Comment by nabla-c0d3** [comment]
Which ARM device do you use for testing? I don't have any so I haven't been able to try your code.

**Comment by Moter8** [comment]
Getting this on 
`Linux c1-10-1-4-39 3.17.0-119 #1 SMP Thu Nov 20 14:15:44 CET 2014 armv7l armv7l armv7l GNU/Linux`
```
shell@c1-10-1-4-39:~/git/nassl_arm$ ./buildAll_arm.py 
Creating dir 2.7 /home/shell/git/nassl_arm/build/openssl-linux32/include/openssl-internal
===BUILDING ZLIB===
Compiler error reporting is too harsh for ./configure (perhaps remove -Werror).
** ./configure aborting.
Traceback (most recent call last):
  File "./buildAll_arm.py", line 92, in <module>
    main()
  File "./buildAll_arm.py", line 57, in main
    perform_build_task('ZLIB', ZLIB_BUILD_TASKS, ZLIB_DIR)
  File "/home/shell/git/nassl_arm/buildAll_config.py", line 35, in perform_build_task
    subprocess.check_call(command, shell=True, cwd=cwd)
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'CFLAGS="-fPIC" ./configure -static' returned non-zero exit status 1
```

**Comment by skydiator** [comment]
@nabla-c0d3 This commit has been tested on ARM PXAxxx, more specifically on Zaurus running Debian Wheezy.

**Comment by skydiator** [comment]
@Moter8 this complains about the dir "openssl-internal" creation. It's either permission issue or the dir "openssl-internal" already exist. It's the same come from the main branch.

**Comment by Moter8** [comment]
@skydiator Thanks, good to know I guess :dart:

**Comment by nabla-c0d3** [comment]
I don't have the time to support another platform, but the build scripts are now a lot more simpler than before and it should be easy to build nassl on ARM without having to change much.

**Pull request closed without merging**
